In [31]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense



In [32]:
# Datos de ejemplo (secuencia de números)
data = [[i] for i in range(100)]

In [33]:
print(data)

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23], [24], [25], [26], [27], [28], [29], [30], [31], [32], [33], [34], [35], [36], [37], [38], [39], [40], [41], [42], [43], [44], [45], [46], [47], [48], [49], [50], [51], [52], [53], [54], [55], [56], [57], [58], [59], [60], [61], [62], [63], [64], [65], [66], [67], [68], [69], [70], [71], [72], [73], [74], [75], [76], [77], [78], [79], [80], [81], [82], [83], [84], [85], [86], [87], [88], [89], [90], [91], [92], [93], [94], [95], [96], [97], [98], [99]]


In [34]:
# Preparar datos para LSTM
def prepare_data(data, n_steps):
    X, y = [], []
    for i in range(len(data)):
        end_ix = i + n_steps
        if end_ix > len(data)-1:
            break
        seq_x, seq_y = data[i:end_ix], data[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return tf.convert_to_tensor(X, dtype=tf.float32), tf.convert_to_tensor(y, dtype=tf.float32)


In [35]:
# Definir hiperparámetros
n_steps = 4
n_features = 1

# Preparar datos
X, y = prepare_data(data, n_steps)

In [36]:
print(X)


tf.Tensor(
[[[ 0.]
  [ 1.]
  [ 2.]
  [ 3.]]

 [[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 2.]
  [ 3.]
  [ 4.]
  [ 5.]]

 [[ 3.]
  [ 4.]
  [ 5.]
  [ 6.]]

 [[ 4.]
  [ 5.]
  [ 6.]
  [ 7.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 6.]
  [ 7.]
  [ 8.]
  [ 9.]]

 [[ 7.]
  [ 8.]
  [ 9.]
  [10.]]

 [[ 8.]
  [ 9.]
  [10.]
  [11.]]

 [[ 9.]
  [10.]
  [11.]
  [12.]]

 [[10.]
  [11.]
  [12.]
  [13.]]

 [[11.]
  [12.]
  [13.]
  [14.]]

 [[12.]
  [13.]
  [14.]
  [15.]]

 [[13.]
  [14.]
  [15.]
  [16.]]

 [[14.]
  [15.]
  [16.]
  [17.]]

 [[15.]
  [16.]
  [17.]
  [18.]]

 [[16.]
  [17.]
  [18.]
  [19.]]

 [[17.]
  [18.]
  [19.]
  [20.]]

 [[18.]
  [19.]
  [20.]
  [21.]]

 [[19.]
  [20.]
  [21.]
  [22.]]

 [[20.]
  [21.]
  [22.]
  [23.]]

 [[21.]
  [22.]
  [23.]
  [24.]]

 [[22.]
  [23.]
  [24.]
  [25.]]

 [[23.]
  [24.]
  [25.]
  [26.]]

 [[24.]
  [25.]
  [26.]
  [27.]]

 [[25.]
  [26.]
  [27.]
  [28.]]

 [[26.]
  [27.]
  [28.]
  [29.]]

 [[27.]
  [28.]
  [29.]
  [30.]]

 [[28.]
  [29.]
  [30.]
  [31.]]

 [[

In [37]:
print(y)

tf.Tensor(
[[ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]
 [24.]
 [25.]
 [26.]
 [27.]
 [28.]
 [29.]
 [30.]
 [31.]
 [32.]
 [33.]
 [34.]
 [35.]
 [36.]
 [37.]
 [38.]
 [39.]
 [40.]
 [41.]
 [42.]
 [43.]
 [44.]
 [45.]
 [46.]
 [47.]
 [48.]
 [49.]
 [50.]
 [51.]
 [52.]
 [53.]
 [54.]
 [55.]
 [56.]
 [57.]
 [58.]
 [59.]
 [60.]
 [61.]
 [62.]
 [63.]
 [64.]
 [65.]
 [66.]
 [67.]
 [68.]
 [69.]
 [70.]
 [71.]
 [72.]
 [73.]
 [74.]
 [75.]
 [76.]
 [77.]
 [78.]
 [79.]
 [80.]
 [81.]
 [82.]
 [83.]
 [84.]
 [85.]
 [86.]
 [87.]
 [88.]
 [89.]
 [90.]
 [91.]
 [92.]
 [93.]
 [94.]
 [95.]
 [96.]
 [97.]
 [98.]
 [99.]], shape=(96, 1), dtype=float32)


In [38]:
# Definir el modelo
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [39]:
# Entrenar el modelo
model.fit(X, y, epochs=200, verbose=0)




In [43]:
y_pred = model.predict(X)
y_pred_classes = np.argmax(y_pred, axis=1)

3/3 [==============================] - 0s 4ms/step - loss: 0.0043


TypeError: cannot unpack non-iterable float object

In [41]:
# Hacer predicciones
x_input = tf.convert_to_tensor([[i] for i in range(100, 104)])
x_input = tf.reshape(x_input, (1, n_steps, n_features))
y_pred = model.predict(x_input, verbose=0)

print("Predicción:", y_pred[0][0])

Predicción: 104.11041
